### PR TITLE
fix: witnesscalc build

### LINKED ISSUE #94: golf: use the lookup into FF inverse method to save constraints
With `circom-witnesscalc`, I made a change that uses `Selector` to do this, but it is pretty inefficient compared to the previous method.

### PR DESCRIPTION
**Pull request by Autoparallel**
To verify this is all working, you can run:
```
build-circuit circuits/aes-gcm/aes-gcm-fold.circom aes-gcm-fold.bin -l node_modules
```
to generate the graph file for witness extension.

To see the constraint count for `aes-gcm-fold`, you can run:
```
circom circuits/aes-gcm/aes-gcm-fold.circom -l node_modules --r1cs
```

---

Currently addresses:
- [x] Closes  https://github.com/pluto/web-prover/issues/215

---
Need to solve:
- [ ] Makes progress towards #93
Which the following may help with:
- [x] Closes #94, addressed with 89da3ee

### CODE REVIEW

**Comment by Autoparallel** [comment]
@0xJepsen @thor314 I will need your help to get this to pass tests and what not.

Also the constraints for `aes-gcm-fold` are now near 1M. We need to reduce this heavily by either folding more or ideally optimizing. Folding more is fine for now. I don't know where the good folding boundaries are, so I'm leaving that for you two to decide on.

**Comment by Autoparallel** [comment]
All tests are passing, but I would appreciate reviewers giving this another look to make sure that this is still totally working as expected.

**Comment by Autoparallel** [comment]
Potentially small improvement noted here

https://github.com/pluto/aes-proof/blob/f0b1dcc094b0456f13a40333273dc88aa192fa4f/circuits/aes-gcm/aes-gcm-foldable.circom#L105

**Review by devloper — APPROVED** [review]
I reviewed this when I updated the tests and confirmed that the changes are working as expected.  From my PoV this is ready to go, the primary blocker atm is that it's dependent on the PP PR (the circuit interface changes)

We can probably merge this now, given that upstream repos should be pinned to a specific version of aes-proof.

**Comment by thor314** [comment]
- `aes-gcm-fold` is difficult to read as is, could use comments
- colin - delete comments
- colin - replace todos
- many magic numbers in `Cipher`, consider replacing with named variables for readability
- ff circom could use some comments to explain the longer but more efficient approach

If helpful, my espanso todo replacement snippets:
```yml
# espanso replace snippet
  - triggers: ["TODO ", "tdd "]
    replace: "TODO(TK {{date}}): "  
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"
  - triggers: ["tdb "]
    replace: "- [ ] TODO(TK {{date}}): "  
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"
  - triggers: ["tdc "]
    replace: "// TODO(TK {{date}}): "  
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"
  - triggers: ["tdp "]
    replace: "TODO(TK): "  

```

**Review by 0xJepsen — APPROVED** [review]
nice work on this

**Review by thor314 — APPROVED** [review]

**Comment by thor314** [comment]
@devloper @Autoparallel Would you annotate your todos:
TODO(<initials> <date>): <comment>

e.g.
TODO(TK 2024-10-21): readability: add comments about what this does

a bare TODO is nice for working alone, but it doesn't say much about how old the thing is for the reader; makes me git blame to see all the relevant metadata

**Pull request merged**
